languageCode = "en-us"
title = "Dylan Meeus"
baseurl = "https://dylanmeeus.github.io"
theme = "hyde-hyde"
enableemoji = true
pygmentsCodeFences = true
pygmentsstyle = "monokai"
googleAnalytics = "UA-172416417-1"

[[menu.menu]]
    name = "Dylan Meeus"

[params.social]
    github = "DylanMeeus"
    twitter = "DylanMeeus"
    linkedin = "dylanmeeus"
    gravatar = "meeusdylan@protonmail.com"

[params]
    mainSections = ["posts", "spanish"]

[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth =  4 

[Social]
    twitter = "DylanMeeus"
