languageCode = "en-us"
title = "Dylan Meeus"
baseurl = "http://it-ca.net/blogdylan"
theme = "m10c"

[params]
    author = "Dylan Meeus"
    description = "Hi! I'm a software engineer currently working with Go in the healthcare sector."

[[params.social]]
    name = "github"
    url = "https://github.com/DylanMeeus"
