languageCode = "en-us"
title = "Dylan Meeus"
baseurl = "https://dylanmeeus.github.io"
theme = "hyde-hyde"
enableemoji = true
pygmentsCodeFences = true
pygmentsstyle = "monokai"

[[menu.menu]]
    name = "Dylan Meeus"

[params.social]
    github = "https://github.com/DylanMeeus"
    twitter = "https://twitter.com/DylanMeeus"
    linkedin = "https://www.linkedin.com/in/dylanmeeus"
    gravatar = "meeusdylan@protonmail.com"
